"""empty message

Revision ID: 276a32dfec62
Revises: e04745e21e9a
Create Date: 2022-11-26 23:03:51.480704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276a32dfec62'
down_revision = 'e04745e21e9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
