"""'v.2.0'

Revision ID: e04745e21e9a
Revises: f23eaec8dd1c
Create Date: 2022-11-13 16:04:57.662009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e04745e21e9a'
down_revision = 'f23eaec8dd1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokenBlockList',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokenBlockList_jti'), 'tokenBlockList', ['jti'], unique=False)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_tokenBlockList_jti'), table_name='tokenBlockList')
    op.drop_table('tokenBlockList')
    # ### end Alembic commands ###
